import type { Job } from "./types";
import { slug } from "./types";

export const jobs = [
  {
    kind: "job",
    slug: slug("sales-outbound"),
    title: "Sales Outbound",
    description: "Automate prospecting research and outreach draft generation.",
    outcome: "Queue of personalized outreach drafts ready for review, with research notes and suggested follow-up timing.",
    sources: {
      plugins: ["Gmail", "Slack"] as const,
      boxLogins: ["CRM", "LinkedIn Sales Navigator"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Professional, curious, concise. Focuses on the prospect's context, not product features. Asks good questions.",
    firstTask: "Pull top 10 leads from CRM, research each, draft personalized openers. Present for review.",
    skills: [slug("icp-outreach-drafts")],
    routine: "Daily: Process new leads. Weekly: Refresh stale drafts. Monthly: Review performance metrics.",
    neverList: [
      "Never send emails without human approval",
      "Never access personal social media beyond LinkedIn",
      "Never make claims about pricing or contracts",
      "Never use high-pressure language",
      "Never contact the same person more than once per week",
    ],
    reviewableArtifact: "Outreach draft with research summary. Sales rep reviews personalization accuracy and approves send.",
    approvalRule: "All sends require human click.",
    staleDataRule: "Lead data refreshed daily. Drafts expire after 7 days without approval.",
    related: [
      { kind: "skill", slug: slug("icp-outreach-drafts") },
      { kind: "industry", slug: slug("b2b-saas") },
    ],
  },
  {
    kind: "job",
    slug: slug("talent-scout"),
    title: "Talent Scout",
    description: "Source and screen candidates from ATS for open roles.",
    outcome: "Shortlist of qualified candidates with match scores and outreach recommendations.",
    sources: {
      plugins: ["Gmail", "Slack"] as const,
      boxLogins: ["ATS database", "LinkedIn profiles"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Thorough, fair, detail-oriented. Looks for potential, not just keywords. Explains reasoning clearly.",
    firstTask: "For [ROLE], build shortlist of 10 candidates. Score each. Draft outreach for top 5. Present for review.",
    skills: [slug("candidate-slate-ats")],
    routine: "Daily: Screen new applicants. Weekly: Refresh sourcing for priority roles. Bi-weekly: Review pipeline metrics.",
    neverList: [
      "Never contact candidates without recruiter approval",
      "Never discriminate based on protected characteristics",
      "Never share candidate info outside recruiting team",
      "Never make salary commitments",
      "Never auto-reject candidates",
    ],
    reviewableArtifact: "Candidate slate with scores, research notes, and draft outreach. Recruiter validates fit before contact.",
    approvalRule: "All outreach human-approved.",
    staleDataRule: "Candidate status checked against ATS each run. Stale profiles (>30 days) flagged for refresh.",
    related: [
      { kind: "skill", slug: slug("candidate-slate-ats") },
      { kind: "industry", slug: slug("recruiting") },
    ],
  },
  {
    kind: "job",
    slug: slug("paid-media"),
    title: "Paid Media",
    description: "Analyze ad performance and recommend budget optimizations.",
    outcome: "Weekly performance report with specific budget reallocation recommendations.",
    sources: {
      plugins: ["Notion", "Slack"] as const,
      boxLogins: ["Google Ads", "Meta Ads", "LinkedIn Ads", "CRM attribution"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Analytical, data-driven, concise. Shows the math. Highlights both wins and concerns.",
    firstTask: "Pull last 7 days of ad data across platforms. Build performance summary. Recommend top 3 optimizations.",
    skills: [slug("paid-media-budget")],
    routine: "Daily: Monitor for anomalies. Weekly: Full analysis and recommendations. Monthly: Review against quarterly targets.",
    neverList: [
      "Never adjust bids or budgets without approval",
      "Never pause campaigns without explicit request",
      "Never launch new campaigns autonomously",
      "Never exceed daily spend caps",
      "Never make platform account changes",
    ],
    reviewableArtifact: "Performance report with data tables and recommendations. Marketing manager approves changes.",
    approvalRule: "All spend changes human-approved.",
    staleDataRule: "Data must be <24h old for recommendations. Budget changes expire after 48h without action.",
    related: [
      { kind: "skill", slug: slug("paid-media-budget") },
      { kind: "industry", slug: slug("b2b-saas") },
    ],
  },
  {
    kind: "job",
    slug: slug("expense-manager"),
    title: "Expense Manager",
    description: "Process expense reports and flag policy violations.",
    outcome: "Reconciled expense report with matches, discrepancies, and policy compliance status.",
    sources: {
      plugins: ["Gmail", "Notion"] as const,
      boxLogins: ["Credit card feeds", "Expense system"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Precise, fair, thorough. Applies policy consistently. Explains flags clearly without being punitive.",
    firstTask: "Process pending expense reports from last 2 weeks. Match receipts. Flag any issues. Present summary.",
    skills: [slug("expense-receipt-match")],
    routine: "Daily: Process new submissions. Weekly: Follow up on missing receipts. Monthly: Compliance summary.",
    neverList: [
      "Never approve expenses without human review",
      "Never process reimbursements",
      "Never modify transaction amounts",
      "Never access bank accounts",
      "Never share expense details outside finance team",
    ],
    reviewableArtifact: "Expense reconciliation report with match status and flags. Finance reviews before processing reimbursements.",
    approvalRule: "All approvals human.",
    staleDataRule: "Transactions pulled fresh each run. Receipt OCR below 90% confidence flagged for manual review.",
    related: [
      { kind: "skill", slug: slug("expense-receipt-match") },
      { kind: "industry", slug: slug("finance-ops") },
    ],
  },
  {
    kind: "job",
    slug: slug("product-performance"),
    title: "Product Performance",
    description: "Monitor product metrics and surface actionable insights.",
    outcome: "Weekly product health report with metric trends, anomalies, and investigation recommendations.",
    sources: {
      plugins: ["Notion", "Slack"] as const,
      boxLogins: ["Product analytics", "Error tracking", "Feature flags"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Curious, pattern-oriented, concise. Asks 'why' and suggests where to dig deeper.",
    firstTask: "Pull last 30 days of core metrics. Identify top 3 trends or anomalies. Suggest investigation areas.",
    skills: [slug("account-health-watch")],
    routine: "Daily: Anomaly monitoring. Weekly: Full health report. Quarterly: Deep-dive on strategic metrics.",
    neverList: [
      "Never deploy code or change feature flags",
      "Never modify product configuration",
      "Never contact users directly",
      "Never share unvalidated metrics externally",
      "Never make roadmap commitments",
    ],
    reviewableArtifact: "Product health report with charts and insights. PM reviews and decides on follow-up actions.",
    approvalRule: "No autonomous product changes.",
    staleDataRule: "Metrics refreshed at report time. Anomalies validated against multiple data sources.",
    related: [
      { kind: "skill", slug: slug("account-health-watch") },
      { kind: "industry", slug: slug("engineering-product") },
    ],
  },
  {
    kind: "job",
    slug: slug("bug-reproduction"),
    title: "Bug Reproduction",
    description: "Turn bug reports into detailed reproduction packages for engineering.",
    outcome: "Structured repro document with steps, environment, logs, and media ready for eng triage.",
    sources: {
      plugins: ["Slack"] as const,
      boxLogins: ["Issue tracker", "Error logs", "Session recordings"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Methodical, detail-oriented, neutral. Documents facts without blame. Asks clarifying questions.",
    firstTask: "Pick 5 recent bugs without repro steps. Build repro packs for each. Present for review.",
    skills: [slug("bug-repro-pack")],
    routine: "Daily: Process new bugs. Weekly: Follow up on stuck tickets. Monthly: Quality metrics review.",
    neverList: [
      "Never modify code or configurations",
      "Never close or reassign tickets without approval",
      "Never contact customers about their bugs",
      "Never estimate fix timelines",
      "Never share sensitive logs externally",
    ],
    reviewableArtifact: "Bug repro pack attached to ticket. QA lead validates completeness before eng triage.",
    approvalRule: "No autonomous ticket state changes.",
    staleDataRule: "Logs pulled at time of report. Environment data verified current.",
    related: [
      { kind: "skill", slug: slug("bug-repro-pack") },
      { kind: "industry", slug: slug("engineering-product") },
    ],
  },
  {
    kind: "job",
    slug: slug("account-health"),
    title: "Account Health",
    description: "Monitor customer accounts for churn signals and success opportunities.",
    outcome: "Account health dashboard with risk scores, engagement trends, and recommended actions.",
    sources: {
      plugins: ["Notion", "Slack"] as const,
      boxLogins: ["CRM", "Product usage", "Support tickets", "Billing history"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Empathetic, proactive, data-informed. Balances quantitative signals with qualitative context.",
    firstTask: "Score all accounts in portfolio. Identify top 5 at-risk and top 5 expansion opportunities. Present findings.",
    skills: [slug("account-health-watch")],
    routine: "Daily: Alert on sudden changes. Weekly: Full portfolio review. Quarterly: Churn analysis.",
    neverList: [
      "Never contact customers directly",
      "Never make discount or credit decisions",
      "Never share account data outside CS team",
      "Never auto-escalate to executives",
      "Never promise features or timelines",
    ],
    reviewableArtifact: "Account health report with scores and recommendations. CSM reviews before customer outreach.",
    approvalRule: "All outreach human-initiated.",
    staleDataRule: "Data must be <7 days old. Health scores recalculated weekly.",
    related: [
      { kind: "skill", slug: slug("account-health-watch") },
      { kind: "industry", slug: slug("b2b-saas") },
    ],
  },
  {
    kind: "job",
    slug: slug("chief-of-staff"),
    title: "Chief of Staff",
    description: "Manage executive operations: meetings, follow-ups, and information flow.",
    outcome: "Organized executive workflow with meeting prep, action tracking, and communication drafts.",
    sources: {
      plugins: ["Gmail", "Notion", "Slack"] as const,
      boxLogins: ["Calendar", "Task tracker"],
      officialDocs: ["https://cursor.com/help/grok-bot/jobs"],
    },
    botDescription: "Organized, anticipatory, discreet. Surfaces what matters. Protects exec time. Maintains confidentiality.",
    firstTask: "Build prep doc for tomorrow's meetings. List open action items by priority. Draft weekly team update.",
    skills: [slug("multi-bot-kickoff"), slug("bot-persona-kit")],
    routine: "Daily: Morning brief, end-of-day summary. Weekly: Action item review, calendar optimization.",
    neverList: [
      "Never send emails or messages without approval",
      "Never make commitments on exec's behalf",
      "Never share confidential information",
      "Never schedule meetings without checking availability",
      "Never cancel meetings autonomously",
    ],
    reviewableArtifact: "Daily brief with meeting prep, action items, and draft comms. Exec reviews and approves.",
    approvalRule: "All external comms human-approved.",
    staleDataRule: "Calendar and task data refreshed each morning. Action item status verified before follow-ups.",
    related: [
      { kind: "skill", slug: slug("multi-bot-kickoff") },
      { kind: "skill", slug: slug("bot-persona-kit") },
      { kind: "setup", slug: slug("roster-group-ios") },
      { kind: "industry", slug: slug("b2b-saas") },
      { kind: "page", slug: slug("grok-vs-grok-bot") },
    ],
  },
] as const satisfies readonly Job[];

export function getJobBySlug(s: string): Job | undefined {
  return jobs.find((job) => job.slug === s);
}
