import type { Setup } from "./types";
import { slug } from "./types";

/**
 * Setup guides catalog.
 * 8 guides covering Grok Bot configuration. Locked slugs per Vera.
 */
export const setupGuides = [
  {
    kind: "setup",
    slug: slug("install-plan"),
    title: "Install Plan",
    description: "Map out your Grok Bot installation before you start.",
    body: "Grok Bot is not Grok chat and not Cursor Cloud Agents. It runs in a shared box tied to your Cursor account (Ultra, Teams Premium, or SuperGrok Heavy required). Before installing, identify which workflows to automate and which data sources you need.",
    steps: [
      { title: "Identify workflows", body: "Pick 2-3 repetitive workflows. Focus on research, drafts, and data organization—not autonomous actions." },
      { title: "List data sources", body: "For each workflow, list which plugins (Gmail, Notion, Slack) and box logins you need. Zoom is broken." },
      { title: "Determine reviewers", body: "Every skill produces a reviewable artifact. Decide who reviews before any action." },
      { title: "Set up test workspace", body: "Create a separate test workspace. Never experiment in production." },
      { title: "Schedule weekly review", body: "For the first month, review bot outputs weekly to catch issues early." },
    ],
    endState: "You have a written plan listing workflows, data sources, reviewers, and a test workspace.",
    commonMiss: "Starting without a test workspace. Bots make mistakes. Review everything first.",
    officialDocs: ["https://cursor.com/bot/onboarding"],
    related: [{ kind: "setup", slug: slug("first-bot") }],
  },
  {
    kind: "setup",
    slug: slug("first-bot"),
    title: "First Bot",
    description: "Create and configure your first Grok Bot instance.",
    body: "A Grok Bot instance runs in the shared box attached to your Cursor account. You configure skills, connect plugins, and set approval rules. The bot produces artifacts for human review—it never sends, spends, publishes, or files autonomously.",
    steps: [
      { title: "Open Grok Bot settings", body: "In Cursor, navigate to Settings > Grok Bot." },
      { title: "Create new bot", body: "Click 'Create New Bot' and choose a descriptive name (e.g., 'Sales-Outbound-Draft')." },
      { title: "Select a skill", body: "Pick one skill from the library to start. Master it before adding more." },
      { title: "Connect plugins", body: "Connect required plugins (Gmail, Notion, Slack). Each requires OAuth." },
      { title: "Run a test task", body: "Run the skill with sample data. Review the output carefully." },
      { title: "Set approval rules", body: "Configure who reviews artifacts before any action is taken." },
    ],
    endState: "A working bot instance with one skill, connected plugins, and approval rules configured.",
    commonMiss: "Skipping the test task. Always verify output quality before real work.",
    officialDocs: ["https://cursor.com/help/grok-bot/first-bot"],
    related: [{ kind: "setup", slug: slug("install-plan") }, { kind: "setup", slug: slug("plugins") }],
  },
  {
    kind: "setup",
    slug: slug("plugins"),
    title: "Plugins",
    description: "Connect Gmail, Notion, and Slack to your Grok Bot.",
    body: "Plugins connect your bot to external services. Only Gmail, Notion, and Slack are verified. Zoom is broken. Each plugin requires OAuth authorization from the service admin.",
    steps: [
      { title: "Open plugin settings", body: "Go to Bot Settings > Plugins." },
      { title: "Add Gmail", body: "Click Add Plugin > Gmail. Complete OAuth with your Google account. Grant read access only to start." },
      { title: "Add Notion", body: "Click Add Plugin > Notion. Authorize workspace access. Select specific pages/databases the bot can read." },
      { title: "Add Slack", body: "Click Add Plugin > Slack. Install the Grok Bot app to your workspace. Select channels for read access." },
      { title: "Test each connection", body: "Run a read-only operation to verify each plugin works." },
    ],
    endState: "Plugins connected with OAuth complete and read-only test verified.",
    commonMiss: "Granting write access before testing read. Start read-only, verify outputs, then expand.",
    officialDocs: ["https://cursor.com/help/grok-bot/plugins"],
    related: [{ kind: "setup", slug: slug("first-bot") }, { kind: "setup", slug: slug("the-box") }],
  },
  {
    kind: "setup",
    slug: slug("the-box"),
    title: "The Box",
    description: "Understand shared boxes and why they don't provide isolation.",
    body: "The box is the execution environment for Grok Bot. It is shared—multiple bots and team members access the same box. Shared box does not mean isolation. If you need true isolation between users, use separate Cursor accounts.",
    steps: [
      { title: "Understand sharing", body: "The box is shared across your Cursor account. All bots see the same data sources once connected." },
      { title: "Configure access controls", body: "Set permissions at the data source level (Gmail labels, Notion pages, Slack channels)." },
      { title: "Separate by sensitivity", body: "Use different bots for sensitive vs. non-sensitive workflows. Same box, different approval rules." },
      { title: "Document access", body: "Maintain a list of who has access to which bots and what data they can reach." },
    ],
    endState: "You understand box sharing and have documented access controls for your team.",
    commonMiss: "Assuming shared box provides user isolation. It does not. Plan accordingly.",
    officialDocs: ["https://docs.x.ai/grok-bot/architecture"],
    related: [{ kind: "setup", slug: slug("plugins") }, { kind: "setup", slug: slug("approvals") }],
  },
  {
    kind: "setup",
    slug: slug("skill-then-routine"),
    title: "Skill Then Routine",
    description: "Master a skill before automating it into a routine.",
    body: "A skill is a single capability. A routine is a scheduled skill. Do not automate until you trust the output. Run the skill manually many times, review every artifact, then convert to a routine with low frequency.",
    steps: [
      { title: "Run manually 10+ times", body: "Execute the skill by hand at least ten times across different inputs." },
      { title: "Review every output", body: "Check each artifact for accuracy, tone, and completeness." },
      { title: "Note edge cases", body: "Document inputs that produce poor outputs. Adjust skill config." },
      { title: "Convert to routine", body: "Once confident, schedule the skill as a routine. Start weekly." },
      { title: "Monitor routine outputs", body: "Review routine artifacts for the first month. Increase frequency only after trust builds." },
    ],
    endState: "Skill runs reliably. Routine scheduled at low frequency with ongoing review.",
    commonMiss: "Automating before mastering. If outputs surprise you, the skill is not ready for routine.",
    officialDocs: ["https://cursor.com/help/grok-bot/routines"],
    related: [{ kind: "skill", slug: slug("teach-a-task") }],
  },
  {
    kind: "setup",
    slug: slug("approvals"),
    title: "Approvals",
    description: "Set up human-in-the-loop approval workflows.",
    body: "Grok Bot never sends, spends, publishes, or files autonomously. Every action that leaves the box requires human approval. Configure approval notifications and train reviewers on what to check.",
    steps: [
      { title: "Identify approval points", body: "List every action where bot output would leave the box (email send, Slack post, Notion publish)." },
      { title: "Configure notifications", body: "Set up Slack or email notifications for pending approvals." },
      { title: "Set timeouts", body: "Configure approval timeout (default 24h). Unapproved items expire." },
      { title: "Define escalation", body: "Specify who gets notified if primary reviewer is unavailable." },
      { title: "Train reviewers", body: "Document what reviewers should check: accuracy, tone, recipients, timing." },
    ],
    endState: "Approval workflow configured with notifications, timeouts, and trained reviewers.",
    commonMiss: "No escalation path. If the reviewer is out, approvals pile up. Always have a backup.",
    officialDocs: ["https://cursor.com/help/grok-bot/approvals"],
    related: [{ kind: "setup", slug: slug("skill-then-routine") }],
  },
  {
    kind: "setup",
    slug: slug("remote-mcp"),
    title: "Remote MCP",
    description: "Connect to external MCP servers over public HTTPS.",
    body: "MCP (Model Context Protocol) lets Grok Bot connect to external tools. Remote MCP requires a public HTTPS endpoint. Internal or VPN endpoints do not work. Authenticate with API keys or OAuth.",
    steps: [
      { title: "Get the HTTPS URL", body: "Obtain the public HTTPS URL for your MCP server. Must be reachable from the internet." },
      { title: "Add MCP connection", body: "Go to Bot Settings > MCP Connections > Add." },
      { title: "Configure auth", body: "Enter API key or set up OAuth flow for the MCP server." },
      { title: "Test read operation", body: "Run a read-only MCP call to verify connection." },
      { title: "Map tools to skills", body: "Configure which MCP tools map to which bot skills." },
    ],
    endState: "MCP connection working with auth configured and tools mapped to skills.",
    commonMiss: "Using internal URLs. Only public HTTPS works. VPN endpoints fail.",
    officialDocs: ["https://docs.x.ai/grok-bot/mcp"],
    related: [{ kind: "skill", slug: slug("remote-mcp-connector") }],
  },
  {
    kind: "setup",
    slug: slug("roster-group-ios"),
    title: "Roster Group iOS",
    description: "Manage bot access and permissions for iOS team members.",
    body: "Roster groups organize team members for access control. Create a group for your iOS team, add members by Cursor account email, and assign bots. Group permissions apply to all members.",
    steps: [
      { title: "Open roster settings", body: "Go to Workspace Settings > Roster." },
      { title: "Create iOS group", body: "Click Create Group. Name it 'iOS Team' or similar." },
      { title: "Add members", body: "Add team members by their Cursor account email." },
      { title: "Assign bots", body: "Select which bots this group can access." },
      { title: "Set permissions", body: "Configure group-level permissions (run skills, view artifacts, approve actions)." },
      { title: "Enable audit log", body: "Turn on audit logging to track group activity." },
    ],
    endState: "iOS team group created with members, bot assignments, permissions, and audit logging.",
    commonMiss: "Email mismatch. Member email must match their Cursor account exactly.",
    officialDocs: ["https://cursor.com/help/grok-bot/roster"],
    related: [{ kind: "setup", slug: slug("the-box") }],
  },
] as const satisfies readonly Setup[];
